# citest 
version: 2
jobs:
  build:
    docker:
      - image: akira6592/ansible:latest
    steps:
      - checkout
      - run:
          name: ansible-lint
          command: "find  ./{1,2}* -name '*.yml' | xargs ansible-lint"

