- hosts: junos
  gather_facts: no
  
  tasks:
    - name: show command test
      junos_command:
        commands:
          - show configuration

      register: result
    - name: save config to file
      copy:
        content: "{{ result.stdout[0] }}"
        dest: "show_config_{{ inventory_hostname }}.txt"
