- hosts: junos
  gather_facts: no

  tasks:
    - name: show command test
      junos_command:
        commands:
          - show interfaces
      register: result
    - name: output csv file
      template:
        src: "./template_interface_junos.txt"
        dest: "./result_interface.csv"
      vars:
        parsed_result: "{{ result.stdout[0] | parse_cli_textfsm('juniper_junos_show_interfaces.template') }}"
