- hosts: ios
  gather_facts: no

  tasks:
    - name: facts
      ios_facts:
        gather_subset: hardware

    - name: template
      template:
        src: facts_list.j2
        dest: facts_list.csv
      run_once: yes
